services:
  frontend:
    build:
      context: ./FrontendDashboard
    ports:
      - "3000:3000"

  backend:
    image: cosmtrek/air
    container_name: go_backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["air"]
